version: '3.7'
services:
  hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - HUB_HOST=hub
      - GRID_MAX_SESSION=5
    networks:
      - selenium-network

  chrome:
    image: selenium/node-chrome
    container_name: selenium-node-chrome
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PORT=4442
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_PORT=5555
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    networks:
      - selenium-network

  firefox:
    image: selenium/node-firefox
    container_name: selenium-node-firefox
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PORT=4442
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_PORT=5555
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge
